# Generated by Django 5.1.1 on 2024-10-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetOTP',
            new_name='OTPGenerator',
        ),
    ]
