# Generated by Django 5.1.1 on 2024-10-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_deposit_userbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerifiactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('phone_number', models.IntegerField()),
                ('profile_photo', models.ImageField(upload_to='profile_img/')),
                ('address', models.CharField(max_length=50)),
                ('city_town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('argentina', 'Argentina'), ('australia', 'Australia'), ('brazil', 'Brazil'), ('canada', 'Canada'), ('china', 'China'), ('colombia', 'Colombia'), ('egypt', 'Egypt'), ('ethiopia', 'Ethiopia'), ('france', 'France'), ('germany', 'Germany'), ('ghana', 'Ghana'), ('greece', 'Greece'), ('india', 'India'), ('indonesia', 'Indonesia'), ('iran', 'Iran'), ('iraq', 'Iraq'), ('ireland', 'Ireland'), ('israel', 'Israel'), ('italy', 'Italy'), ('ivory_coast', 'Ivory Coast'), ('japan', 'Japan'), ('kenya', 'Kenya'), ('malaysia', 'Malaysia'), ('mexico', 'Mexico'), ('morocco', 'Morocco'), ('nepal', 'Nepal'), ('netherlands', 'Netherlands'), ('new_zealand', 'New Zealand'), ('nigeria', 'Nigeria'), ('norway', 'Norway'), ('pakistan', 'Pakistan'), ('peru', 'Peru'), ('philippines', 'Philippines'), ('poland', 'Poland'), ('portugal', 'Portugal'), ('qatar', 'Qatar'), ('russia', 'Russia'), ('saudi_arabia', 'Saudi Arabia'), ('singapore', 'Singapore'), ('south_africa', 'South Africa'), ('south_korea', 'South Korea'), ('spain', 'Spain'), ('sri_lanka', 'Sri Lanka'), ('sweden', 'Sweden'), ('switzerland', 'Switzerland'), ('thailand', 'Thailand'), ('turkey', 'Turkey'), ('united_kingdom', 'United Kingdom'), ('united_states', 'United States'), ('vietnam', 'Vietnam')], default='argentina', max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('successful', 'Successful')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferal', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
