# Generated by Django 5.1.1 on 2024-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userverifiactiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverifiactiondetails',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
