# Generated by Django 5.1.1 on 2024-10-07 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userverifiactiondetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCverification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('proof_selfie', models.ImageField(upload_to='kyc/')),
                ('font_side', models.ImageField(upload_to='kyc/')),
                ('back_side', models.ImageField(upload_to='kyc/')),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
