# Generated by Django 5.1.1 on 2024-10-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.paymentmethod'),
        ),
    ]
