# Generated by Django 5.1.1 on 2024-10-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_deposit_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverifiactiondetails',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userverifiactiondetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
