# Generated by Django 5.1.1 on 2024-10-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_investmentplan_userinvestment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='Investment_paln',
            new_name='Investment_plan',
        ),
    ]
