# Generated by Django 5.1.1 on 2024-10-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_investment_paln_userinvestment_investment_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='Investment_plan',
            new_name='investment_plan',
        ),
    ]
