# Generated by Django 5.1.1 on 2024-10-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_investment_plan_userinvestment_investment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
