# Generated by Django 5.1.1 on 2024-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_investmentintrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
