# Generated by Django 5.1.1 on 2024-10-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
