# Generated by Django 5.1.1 on 2024-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_bonus_created_at_bonus_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='total_intrest_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
