# Generated by Django 5.1.1 on 2024-10-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_userinvestment_total_intrest_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='total_intrest_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
