# Generated by Django 5.1.1 on 2024-10-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_userinvestment_total_intrest_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='cashout',
            field=models.BooleanField(default=False),
        ),
    ]
