# Generated by Django 5.1.1 on 2024-10-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_historicaluserbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUserBalance',
        ),
    ]
