# Generated by Django 5.1.1 on 2024-10-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_delete_historicaluserbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
