# Generated by Django 5.1.1 on 2024-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
