# Generated by Django 5.1.1 on 2024-10-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_commission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverifiactiondetails',
            name='ssn',
        ),
    ]
