# Generated by Django 5.1.1 on 2024-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_userverifiactiondetails_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverifiactiondetails',
            name='referral',
        ),
        migrations.AddField(
            model_name='userverifiactiondetails',
            name='ssn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
