# Generated by Django 5.1.1 on 2024-10-20 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_userverifiactiondetails_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referrers', to=settings.AUTH_USER_MODEL),
        ),
    ]
