# Generated by Django 5.1.1 on 2024-10-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_disableaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
