# Generated by Django 5.1.1 on 2024-10-20 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_rawpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawpassword',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rawpassword',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='rawpassword',
            name='user_name',
        ),
        migrations.AddField(
            model_name='rawpassword',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rawpassword',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
