# Generated by Django 5.1.1 on 2024-10-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
            ],
        ),
    ]
