# Generated by Django 5.1.2 on 2024-10-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='balance_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
