# Generated by Django 5.1.2 on 2024-10-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_userinvestment_balance_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userverifiactiondetails',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
