# Generated by Django 5.1.2 on 2024-11-09 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_deposit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
