# Generated by Django 5.1.2 on 2024-11-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_withdraw_wallet_name_alter_withdraw_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='plan_id',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
