# Generated by Django 5.1.2 on 2024-11-17 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_userinvestment_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
