# Generated by Django 5.1.2 on 2024-11-20 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_userinvestment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
