# Generated by Django 5.1.2 on 2024-12-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_walletaddress_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletaddress',
            old_name='transaction_id',
            new_name='wallet_id',
        ),
    ]
