# Generated by Django 5.1.2 on 2024-12-06 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_rename_transaction_id_walletaddress_wallet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_country', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('united states dollar', 'United States Dollar'), ('euro', 'Euro'), ('british pound', 'British Pound'), ('japanese yen', 'Japanese Yen'), ('canadian dollar', 'Canadian Dollar'), ('australian dollar', 'Australian Dollar'), ('swiss franc', 'Swiss Franc'), ('chinese yuan', 'Chinese Yuan'), ('swedish krona', 'Swedish Krona'), ('new zealand dollar', 'New Zealand Dollar'), ('mexican peso', 'Mexican Peso'), ('singapore dollar', 'Singapore Dollar'), ('hong kong dollar', 'Hong Kong Dollar'), ('norwegian krone', 'Norwegian Krone'), ('south korean won', 'South Korean Won'), ('russian ruble', 'Russian Ruble'), ('indian rupee', 'Indian Rupee'), ('brazilian real', 'Brazilian Real'), ('south african rand', 'South African Rand'), ('turkish lira', 'Turkish Lira')], max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
