# Generated by Django 5.1.2 on 2024-12-07 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_card_id', models.CharField(blank=True, max_length=16, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=50)),
                ('name_on_card', models.CharField(max_length=50)),
                ('expiration_date', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
