# Generated by Django 5.1.2 on 2024-12-07 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
