# Generated by Django 5.1.2 on 2024-12-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_bankcard_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcard',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
