# Generated by Django 5.1.2 on 2024-12-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_withdraw_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='payment_method_type',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
