# Generated by Django 5.1.2 on 2024-12-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_remove_withdraw_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
