# Generated by Django 5.1.2 on 2024-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_email_delivery_status_userreferral_userscommissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ERC20', 'ERC20'), ('DOT', 'DOT'), ('BEP2', 'BEP2'), ('BEP20', 'BEP20'), ('ERC20', 'ERC20'), ('OMNI', 'OMNI'), ('TRC20', 'TRC20')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
