# Generated by Django 5.1.2 on 2025-01-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_paymentmethod_network_paymentmethod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='plan_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
