# Generated by Django 5.1.2 on 2025-04-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_investmentplan_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='duration_span',
            field=models.CharField(blank=True, choices=[('hour(s)', 'Hour(s)'), ('day(s)', 'Day(s)'), ('week(s)', 'Week(s)'), ('month(s)', 'Month(s)'), ('year(s)', 'Year(s)')], max_length=20, null=True),
        ),
    ]
